version: '3.7'

services:
    app:
        container_name: sboard_task_api
        build:
            context: .
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run start:dev
        env_file:
            - .env
        ports:
            - "10000:10000"
        restart: always

    pgsql:
        container_name: sboard_task_postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: ${PG_DATABASE}
            POSTGRES_USER: ${PG_USERNAME}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - "5432:5432"

networks:
    back:
volumes:
    app:
